name: Build PPMA

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: eried/portapack-mayhem-build:latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build PPMA
        run: |
          mkdir build && cd build
          cmake ..
          make

      - name: Upload PPMA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: friendly-talker-ppma
          path: build/*.ppma
